using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace IconPacks.Generator;

[Generator]
public class WpfGeometryGenerator : IIncrementalGenerator
{
    private const string AttributeName = "IconPacks.Generator.WpfGeometryConverterAttribute";

    private const string AttributeText = """

        namespace IconPacks.Generator;

        using System;

        [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
        public sealed class WpfGeometryConverterAttribute(Type type) : Attribute
        {
            public Type Type { get; } = type;
        }

        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource(
                "WpfGeometryConverterAttribute.g.cs",
                SourceText.From(AttributeText, Encoding.UTF8)
            )
        );

        var classDeclarations = context
            .SyntaxProvider.CreateSyntaxProvider(
                predicate: (s, _) => IsClassWithAttribute(s),
                transform: (ctx, _) => GetClassModel(ctx)
            )
            .Where(m => m != null);

        context.RegisterSourceOutput(classDeclarations, GenerateCode);
    }

    private static bool IsClassWithAttribute(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax { AttributeLists.Count: > 0 };
    }

    private static (ISymbol, ITypeSymbol)? GetClassModel(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        var selfSymbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration);

        if (selfSymbol == null)
            return null;

        var attr = selfSymbol
            .GetAttributes()
            .Where(ad => ad.AttributeClass?.ToDisplayString() == AttributeName)
            .FirstOrDefault();

        if (attr is null)
            return null;

        if (attr.ConstructorArguments[0].Value is ITypeSymbol sourceSymbol)
        {
            return (selfSymbol, sourceSymbol);
        }

        return null;
    }

    private static void GenerateCode(
        SourceProductionContext context,
        (ISymbol, ITypeSymbol)? symbols
    )
    {
        if (symbols == null)
            return;

        var (selfSymbol, sourceSymbol) = symbols.Value;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System.Windows.Media;");
        sb.AppendLine();
        sb.AppendLine($"namespace {selfSymbol.ContainingNamespace.ToDisplayString()}");
        sb.AppendLine("{");
        sb.AppendLine(
            $"    {(selfSymbol.IsStatic ? "static " : string.Empty)}partial class {selfSymbol.Name}"
        );
        sb.AppendLine("    {");

        var fields = sourceSymbol
            .GetMembers()
            .Where(member =>
                member is IFieldSymbol { IsStatic: true }
                || member is IFieldSymbol { IsConst: true }
            )
            .ToList();

        foreach (var field in fields)
        {
            sb.AppendLine(
                $"        public static Geometry {field.Name} => Geometry.Parse({sourceSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}.{field.Name});"
            );
        }

        sb.AppendLine();
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource(
            $"{selfSymbol.Name}.GeometrySource.Wpf.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8)
        );
    }
}
